import { test, expect, type Page } from '@playwright/test'
import { chooseTvOption } from './tv-select'

const backend = 'http://127.0.0.1:5174'
async function login(page: Page) {
  await page.goto('/')
  await page.locator('[data-nav-id="nav-profile"]').click()
  await expect(page.getByLabel('Логин или e-mail')).toBeFocused()
  await page.getByLabel('Логин или e-mail').fill('demo@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('demo-only')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Выйти из аккаунта', exact: true })).toBeVisible()
  await page.locator('[data-nav-id="nav-home"]').click()
  await expect(page.getByRole('heading', { name: 'Что посмотрим сегодня?' })).toBeVisible()
}
async function playSeries(page: Page) {
  await page.locator('[data-nav-id="continue-100"]').click()
  await page.locator('[data-nav-id="detail-play"]').click()
  await expect(page.getByRole('dialog', { name: 'Продолжить просмотр?' })).toBeVisible()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
}
test.beforeEach(async ({ request }) => { await request.post(backend + '/api/test/reset') })

test('failed login stays logged out, clears the password, and recovers', async ({ page, request }) => {
  expect((await request.get('/.state/test-video.mp4')).status()).toBe(403)
  await page.goto('/')
  await page.locator('[data-nav-id="nav-profile"]').click()
  await expect(page.getByText('ТЕСТОВЫЙ РЕЖИМ', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Логин или e-mail')).toBeFocused()
  await page.getByLabel('Логин или e-mail').fill('demo@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('отклонил')
  await expect(page.getByLabel('Пароль', { exact: true })).toHaveValue('')
  await page.getByLabel('Пароль', { exact: true }).fill('demo-only')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Выйти из аккаунта', exact: true })).toBeVisible()
  await page.locator('[data-nav-id="nav-home"]').click()
  await expect(page.getByRole('heading', { name: 'Что посмотрим сегодня?' })).toBeVisible()
})

test('home order, keyboard navigation, and Back restore the selected card', async ({ page }) => {
  await login(page)
  await expect(page.locator('.section-heading h2')).toHaveText(['Продолжить просмотр', 'Мои закладки', 'Новинки', 'Популярное'])
  await page.locator('[data-nav-id="nav-series"]').click()
  const card = page.locator('[data-nav-id="catalog-100"]')
  await card.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('[data-nav-id="detail-play"]')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(card).toBeFocused()
  await page.locator('[data-nav-id="nav-search"]').focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('[data-nav-id="nav-bookmarks"]')).toBeFocused()
})

test('a slow old search cannot overwrite the latest results', async ({ page }) => {
  await login(page)
  await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  await input.fill('slow')
  await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await input.fill('фильм')
  await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await expect(page.locator('[data-nav-id="search-200"]')).toBeVisible()
  await expect(page.locator('[data-nav-id="search-100"]')).toHaveCount(0)
  await page.waitForTimeout(650)
  await expect(page.locator('[data-nav-id="search-200"]')).toBeVisible()
  await expect(page.locator('[data-nav-id="search-100"]')).toHaveCount(0)
})

test('bookmark mutation is reflected in server state and reloaded list', async ({ page, request }) => {
  await login(page)
  await page.locator('[data-nav-id="new-200"]').click()
  await page.locator('[data-nav-id="detail-bookmark"]').click()
  await page.getByRole('button', { name: 'Добавить', exact: true }).click()
  await expect.poll(async () => (await (await request.get(backend + '/api/test/state')).json()).bookmarks).toContain('200')
  await page.locator('[data-nav-id="nav-bookmarks"]').click()
  await expect(page.locator('[data-nav-id="bookmarks-200"]')).toBeVisible()
})

test('resume loads local position, remote seeks 10 seconds and closing saves', async ({ page, request }) => {
  await login(page)
  await playSeries(page)
  await page.locator('.player-stage').click()
  const before = await page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)
  expect(before).toBeGreaterThanOrEqual(25)
  await page.locator('.player-stage').focus()
  await page.keyboard.press('ArrowRight')
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBeCloseTo(before + 10, 0)
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(0)
  await expect.poll(async () => (await (await request.get(backend + '/api/test/state')).json()).progress['100'].position).toBeGreaterThan(34)
})

test('failed progress keeps a quiet recovery control after leaving the player', async ({ page, request }) => {
  await login(page)
  await playSeries(page)
  await request.post(backend + '/api/test/fail-save')
  await page.locator('.player-stage').click()
  await expect(page.locator('.player').getByRole('button', { name: 'Повторить сохранение просмотра', exact: true })).toBeVisible()
  await page.locator('.player-stage').focus()
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Проверить сохранение просмотра', exact: true })).toBeVisible()
  await request.post(backend + '/api/test/fail-save?value=false')
  await page.getByRole('button', { name: 'Проверить сохранение просмотра', exact: true }).click()
  await page.getByRole('button', { name: 'Повторить сохранение', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Проверить сохранение просмотра', exact: true })).toHaveCount(0)
  await expect.poll(async () => (await (await request.get(backend + '/api/test/state')).json()).saves.length).toBeGreaterThan(0)
})

test('quality/subtitles survive episode completion and cancelled auto-next', async ({ page, request }) => {
  await login(page)
  await page.locator('[data-nav-id="continue-100"]').click()
  await page.locator('[data-nav-id="detail-play"]').click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
  await chooseTvOption(page, page.getByRole('combobox', { name: 'Субтитры', exact: true }), 'ru')
  await chooseTvOption(page, page.getByRole('combobox', { name: 'Качество', exact: true }), '360p')
  await expect.poll(() => page.locator('video').evaluate(element => element.textTracks[0]?.mode)).toBe('showing')
  await expect.poll(() => page.locator('video').evaluate(element => (element as HTMLVideoElement).duration)).toBeGreaterThan(0)
  await page.locator('video').evaluate(async element => { const video = element as HTMLVideoElement; video.currentTime = video.duration - 0.1; await video.play() })
  await expect(page.getByRole('button', { name: 'Отменить переход', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Отменить переход', exact: true }).click()
  await page.locator('.player-stage').focus()
  await page.keyboard.press('Escape')
  await expect.poll(async () => (await (await request.get(backend + '/api/test/state')).json()).progress['100'].completed).toBe(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Что посмотрим сегодня?' })).toBeVisible()
  const preferences = await page.evaluate(() => JSON.parse(localStorage.getItem('rezka.preferences') || '{}'))
  expect(preferences.quality).toBe('360p')
  expect(preferences.subtitleId).toBe('ru')
  expect(preferences.translatorId).toBe('1')
})
