import { test, expect, type Page } from '@playwright/test'

async function openPausedPlayer(page: Page, selectedEpisode = 1) {
  await page.route('**/api/rpc', async route => {
    if (route.request().postDataJSON().method === 'progress') await route.fulfill({ json: { returnValue: true, result: null } })
    else await route.continue()
  })
  await page.goto('/')
  await page.locator('[data-nav-id="nav-profile"]').click()
  await expect(page.getByLabel('Логин или e-mail')).toBeFocused()
  await page.getByLabel('Логин или e-mail').fill('demo@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('demo-only')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Выйти из аккаунта', exact: true })).toBeVisible()
  await page.locator('[data-nav-id="nav-home"]').click()
  await page.locator('[data-nav-id="continue-100"]').click()
  if (selectedEpisode !== 1) await page.locator(`[data-nav-id="episode-1-${selectedEpisode}"]`).click()
  await page.locator('[data-nav-id="detail-play"]').click()
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).paused)).toBe(false)
  await page.locator('video').evaluate(v => { const video = v as HTMLVideoElement; video.pause(); video.currentTime = 30 })
  await expect(page.getByRole('slider', { name: 'Позиция видео' })).toHaveValue('30')
}
test.beforeEach(async ({ request }) => { await request.post('http://127.0.0.1:5174/api/test/reset') })

test('Back needs two distinct presses to leave active playback', async ({ page }) => {
  await openPausedPlayer(page)
  await page.locator('.player-stage').focus()
  await page.evaluate(() => {
    const event = () => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }))
    event(); event()
  })
  await expect(page.locator('video')).toHaveCount(1)
  await expect(page.locator('.player-back-hint')).toContainText('Нажмите Back ещё раз')
  await page.evaluate(() => document.dispatchEvent(new KeyboardEvent('keyup', { key: 'Escape', bubbles: true })))
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.player-back-hint')).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(1)
  await page.keyboard.press('Escape')
  await expect(page.locator('video')).toHaveCount(0)
})

test('horizontal seek focuses timeline then play/pause; two Down presses hide controls', async ({ page }) => {
  await openPausedPlayer(page)
  const stage = page.locator('.player-stage')
  const range = page.getByRole('slider', { name: 'Позиция видео' })
  const toggle = page.getByRole('button', { name: 'Воспроизвести', exact: true })
  await stage.focus(); await page.keyboard.press('ArrowRight')
  await expect(range).toBeFocused()
  await expect(range).toHaveValue('40')
  await page.keyboard.press('ArrowDown'); await expect(toggle).toBeFocused()
  await page.keyboard.press('ArrowDown'); await expect(stage).toBeFocused()
  await expect(page.locator('.player-overlay')).toHaveClass(/controls-hidden/)
  await page.keyboard.press('ArrowUp'); await expect(toggle).toBeFocused()
  await page.keyboard.press('ArrowUp'); await expect(range).toBeFocused()
  await page.keyboard.press('ArrowUp'); await expect(stage).toBeFocused()
  await expect(page.locator('.player-overlay')).toHaveClass(/controls-hidden/)
  await page.keyboard.press('ArrowDown'); await expect(range).toBeFocused()
  expect(await page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBe(40)
  await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter')
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).paused)).toBe(false)
  await expect(page.getByRole('button', { name: 'Пауза', exact: true })).toBeFocused()
  await expect(page.locator('video')).toBeVisible()
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape'); await expect(page.locator('video')).toHaveCount(0)
})

test('action-row arrows navigate icons without seeking and timeline vertical arrows keep time', async ({ page }) => {
  await openPausedPlayer(page)
  const range = page.getByRole('slider', { name: 'Позиция видео' })
  const quality = page.locator('.player').getByRole('combobox', { name: 'Качество', exact: true })
  const toggle = page.getByRole('button', { name: 'Воспроизвести', exact: true })
  const next = page.getByRole('button', { name: 'Следующая серия', exact: true })
  const subtitles = page.locator('.player').getByRole('combobox', { name: 'Субтитры', exact: true })
  const format = page.getByRole('button', { name: 'Формат экрана', exact: true })
  await range.focus(); await page.keyboard.press('ArrowDown'); await expect(toggle).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(next).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(quality).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(subtitles).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(format).toBeFocused()
  await page.keyboard.press('ArrowRight'); await expect(format).toBeFocused()
  await quality.focus(); await page.keyboard.press('ArrowLeft'); await expect(next).toBeFocused()
  await page.keyboard.press('ArrowLeft'); await expect(toggle).toBeFocused()
  await page.keyboard.press('ArrowUp'); await expect(range).toBeFocused()
  expect(await page.locator('video').evaluate(v => (v as HTMLVideoElement).currentTime)).toBe(30)
})

test('holding Down advances one player zone and blur clears the latch', async ({ page }) => {
  await openPausedPlayer(page)
  const stage = page.locator('.player-stage')
  const range = page.getByRole('slider', { name: 'Позиция видео' })
  await stage.focus()
  for (let index = 0; index < 6; index++) {
    await page.evaluate(() => document.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', keyCode: 40, repeat: false, bubbles: true, cancelable: true })))
    await page.waitForTimeout(50)
  }
  await expect(range).toBeFocused()
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('button', { name: 'Воспроизвести', exact: true })).toBeFocused()
})

test('previous and next episode actions are ordered left of playback settings', async ({ page }) => {
  await openPausedPlayer(page, 2)
  const row = page.locator('.control-row')
  await expect(row.locator('.episode-actions').getByRole('button')).toHaveCount(3)
  await expect(row.locator('.episode-actions').getByRole('button').nth(0)).toHaveAttribute('aria-label', 'Предыдущая серия')
  await expect(row.locator('.episode-actions').getByRole('button').nth(1)).toHaveAttribute('aria-label', 'Воспроизвести')
  await expect(row.locator('.episode-actions').getByRole('button').nth(2)).toHaveAttribute('aria-label', 'Следующая серия')
  await expect(row.locator('.playback-actions').getByRole('combobox')).toHaveCount(2)
  await expect(row.locator('.playback-actions').getByRole('button', { name: 'Формат экрана', exact: true })).toBeVisible()
  const previousBox = await page.getByRole('button', { name: 'Предыдущая серия', exact: true }).boundingBox()
  const qualityBox = await page.getByRole('combobox', { name: 'Качество', exact: true }).boundingBox()
  expect(previousBox!.x).toBeLessThan(qualityBox!.x)
  await page.getByRole('button', { name: 'Предыдущая серия', exact: true }).click()
  await expect(page.locator('.player-heading')).toContainText('Серия 1')
  await expect(page.getByRole('button', { name: 'Предыдущая серия', exact: true })).toHaveCount(0)
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
  await expect(page.locator('.player-skeleton')).toHaveCount(0)
  await page.getByRole('button', { name: 'Следующая серия', exact: true }).click()
  await expect(page.locator('.player-heading')).toContainText('Серия 2')
  await expect.poll(() => page.locator('video').evaluate(v => (v as HTMLVideoElement).readyState)).toBeGreaterThanOrEqual(2)
  await page.locator('.player-stage').focus(); await page.keyboard.press('Escape'); await page.keyboard.press('Escape')
  await expect(page.locator('[data-nav-id="episode-1-2"]')).toHaveAttribute('aria-pressed', 'true')
})

test('direct icon quality shows actual selected resolution and one check, without max or extra player selectors', async ({ page }) => {
  await openPausedPlayer(page)
  const quality = page.locator('.player').getByRole('combobox', { name: 'Качество', exact: true })
  await expect(quality).toHaveAttribute('data-value', '720p')
  await expect(quality.locator('svg')).toHaveCount(1)
  await expect(quality).toHaveText('')
  const subtitles = page.locator('.player').getByRole('combobox', { name: 'Субтитры', exact: true })
  await expect(subtitles.locator('svg')).toHaveCount(1)
  await expect(subtitles).toHaveAttribute('data-value', '')
  await expect(page.locator('.player').getByRole('combobox')).toHaveCount(2)
  await quality.click()
  await expect(page.getByRole('option').and(page.locator('[data-value="max"]'))).toHaveCount(0)
  const selected = page.getByRole('option', { selected: true })
  await expect(selected).toHaveCount(1)
  await expect(selected).toHaveAttribute('data-value', '720p')
  await expect(selected.locator('[aria-hidden="true"]')).toHaveText('✓')
  await page.keyboard.press('Escape'); await expect(quality).toBeFocused()
})
