import { test, expect } from '@playwright/test'

const backend = 'http://127.0.0.1:5174'
const guestHistoryKey = 'rezka.search-history.https%3A%2F%2Fhdrezka-home.tv.guest'
test.beforeEach(async ({ request }) => { await request.post(backend + '/api/test/reset') })

test('submitted searches persist uniquely and can be run again from Search', async ({ page }) => {
  const calls: string[] = []
  await page.route('**/api/rpc', async route => {
    const body = route.request().postDataJSON()
    if (body.method === 'search') calls.push(body.params.query)
    await route.fallback()
  })
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  await input.fill('авто')
  await expect.poll(() => calls).toContain('авто')
  expect(await page.evaluate(key => localStorage.getItem(key), guestHistoryKey)).toBeNull()
  await page.getByRole('button', { name: 'Найти', exact: true }).click()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) || '[]'), guestHistoryKey)).toEqual(['авто'])
  await input.fill('дюна'); await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await input.fill('авто'); await page.getByRole('button', { name: 'Найти', exact: true }).click()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key) || '[]'), guestHistoryKey)).toEqual(['авто', 'дюна'])

  await page.reload(); await page.locator('[data-nav-id="nav-search"]').click()
  const history = page.getByRole('region', { name: 'Недавние запросы' })
  await expect(history.locator('.search-history-query')).toHaveText(['авто', 'дюна'])
  await history.getByRole('button', { name: 'дюна', exact: true }).click()
  await expect(input).toHaveValue('дюна')
  await expect.poll(() => calls.filter(query => query === 'дюна').length).toBeGreaterThanOrEqual(2)
  await history.getByRole('button', { name: 'Очистить', exact: true }).click()
  await expect(history).toHaveCount(0)
  await expect(input).toBeFocused()
  expect(await page.evaluate(key => localStorage.getItem(key), guestHistoryKey)).toBeNull()
})

test('search history is bounded to six safe labels', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify(['1', '', 3, '2', '3', '4', '5', '6', '7', 'x'.repeat(200)])), guestHistoryKey)
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  await expect(page.getByRole('region', { name: 'Недавние запросы' }).locator('.search-history-query')).toHaveText(['1', '2', '3', '4', '5', '6'])
})

test('guest and account search histories stay isolated on a shared TV', async ({ page }) => {
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  await input.fill('гостевой запрос'); await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await page.locator('[data-nav-id="nav-profile"]').click()
  await page.getByLabel('Логин или e-mail').fill('demo@example.test')
  await page.getByLabel('Пароль', { exact: true }).fill('demo-only')
  await page.getByRole('button', { name: 'Войти', exact: true }).click()
  await page.locator('[data-nav-id="nav-search"]').click()
  await expect(page.getByRole('region', { name: 'Недавние запросы' })).toHaveCount(0)
  await input.fill('запрос аккаунта'); await page.getByRole('button', { name: 'Найти', exact: true }).click()
  await page.locator('[data-nav-id="nav-profile"]').click(); await page.getByRole('button', { name: 'Выйти из аккаунта', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Выйти', exact: true }).click()
  await page.locator('[data-nav-id="nav-search"]').click()
  await expect(page.getByRole('region', { name: 'Недавние запросы' }).locator('.search-history-query')).toHaveText(['гостевой запрос'])
})

test('D-pad reaches Find and Clear without reopening the search input', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, JSON.stringify(['дюна', 'аватар'])), guestHistoryKey)
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  const find = page.getByRole('button', { name: 'Найти', exact: true })
  const clear = page.getByRole('button', { name: 'Очистить', exact: true })
  const queries = page.getByRole('region', { name: 'Недавние запросы' }).locator('.search-history-query')
  await expect(input).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(queries.first()).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(find).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(queries.first()).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(queries.nth(1)).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(clear).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(find).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(input).toBeFocused()
})

test('Right leaves the search field only when the caret reaches the end', async ({ page }) => {
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  await input.fill('гладиатор')
  await input.evaluate((element: HTMLInputElement) => element.setSelectionRange(3, 3))
  await page.keyboard.press('ArrowRight')
  await expect(input).toBeFocused()
  expect(await input.evaluate((element: HTMLInputElement) => element.selectionStart)).toBe(4)
  await input.evaluate((element: HTMLInputElement) => element.setSelectionRange(element.value.length, element.value.length))
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('button', { name: 'Найти', exact: true })).toBeFocused()
})

test('Down from search still reaches results when there is no history', async ({ page }) => {
  await page.goto('/'); await page.locator('[data-nav-id="nav-search"]').click()
  const input = page.getByLabel('Название фильма или сериала')
  await input.fill('тест')
  await expect(page.locator('.poster-grid .poster-card').first()).toBeVisible()
  await expect(page.getByRole('region', { name: 'Недавние запросы' })).toHaveCount(0)
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.poster-grid .poster-card').first()).toBeFocused()
})
